In [2]:
# Import section
import pandas as pd
import numpy as np
import zipfile
import requests
from io import BytesIO

In [1]:
pip install selenium

Requirement already satisfied: selenium in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (4.7.2)
Requirement already satisfied: trio-websocket~=0.9 in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[socks]~=1.26 in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from selenium) (1.26.9)
Requirement already satisfied: trio~=0.17 in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from selenium) (0.22.0)
Requirement already satisfied: certifi>=2021.10.8 in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from selenium) (2022.12.7)
Requirement already satisfied: sortedcontainers in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: async-generator>=1.9 in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: attrs>=19.2.0 in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: sniffio in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: wsproto>=0.14 in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /Users/mohjaiswal/opt/anaconda3/lib/python3.9/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
conda install -c conda-forge firefox geckodriver

Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/mohjaiswal/opt/anaconda3

  added / updated specs:
    - firefox
    - geckodriver


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    firefox-109.0              |       hf0c8a7f_0       102.8 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       102.8 MB

The following packages will be UPDATED:

  firefox                                108.0.2-hf0c8a7f_0 --> 109.0-hf0c8a7f_0



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(740): An error occurred while uninstalling package 'conda-forge/osx-64::firefox-108.0.2-hf0c8a7f_0'.
Rolling back transaction: done

[Errno 1] Operation not permitted: '/Users/mohjaiswal/opt/anaconda3/bin/FirefoxApp/Contents/MacOS/plugin-container.app/Contents/Info.plist.c~'
()


Note: you may need to restart the kernel to use updated packages.

In [4]:
# Using the read_csv function and Path module, create a DataFrame 
# by importing the sfo_neighborhoods_census_data.csv file from the Resources folder
asset_data_df = requests.get("https://www150.statcan.gc.ca/n1/tbl/csv/46100062-eng.zip")

In [5]:
with zipfile.ZipFile(BytesIO(asset_data_df.content)) as zip_file:
# Extract the file by name
    csv_file = '46100062.csv'
    with zip_file.open(csv_file) as csv_file_opened:
        home_prices_df = pd.read_csv(csv_file_opened, header=0, sep=',', quotechar='"')

In [6]:
# Review the first and last five rows of the DataFrame
display(home_prices_df.head(),home_prices_df.tail())

,REF_DATE,GEO,DGUID,Number of buyers as part of a property sale,Age groups,First-time home buyer status,Buyer characteristics,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2018,Nova Scotia,2016A000212,"Total, all number of buyers categories","Total, all age groups","Total, all home buyers categories","Total, all sex of property buyer categories",Number of property buyers,Number,223,units,0,v1340366522,1.1.1.1.1.1,21480.0,NaN,NaN,NaN,0
1,2018,Nova Scotia,2016A000212,"Total, all number of buyers categories","Total, all age groups","Total, all home buyers categories","Total, all sex of property buyer categories",Average total income of property buyer,Dollars,81,units,0,v1340366525,1.1.1.1.1.2,70000.0,NaN,NaN,NaN,0
2,2018,Nova Scotia,2016A000212,"Total, all number of buyers categories","Total, all age groups","Total, all home buyers categories","Total, all sex of property buyer categories",Median total income of property buyer,Dollars,81,units,0,v1340366526,1.1.1.1.1.3,55000.0,NaN,NaN,NaN,0
3,2018,Nova Scotia,2016A000212,"Total, all number of buyers categories","Total, all age groups","Total, all home buyers categories","Total, all sex of property buyer categories",Average family total income,Dollars,81,units,0,v1340366527,1.1.1.1.1.4,130000.0,NaN,NaN,NaN,0
4,2018,Nova Scotia,2016A000212,"Total, all number of buyers categories","Total, all age groups","Total, all home buyers categories","Total, all sex of property buyer categories",Median family total income,Dollars,81,units,0,v1340366528,1.1.1.1.1.5,105000.0,NaN,NaN,NaN,0

,REF_DATE,GEO,DGUID,Number of buyers as part of a property sale,Age groups,First-time home buyer status,Buyer characteristics,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
17795707,2019,"Yukon, Unorganized, Unorganized",2016A00056001045,Buyer in a group of three or more,55 years old and over,Not first-time home buyer,Admission category not applicable (non-immigrant),Median sale price,Dollars,81,units,0,v1348497719,733.4.4.3.25.7,NaN,..,NaN,NaN,0
17795708,2019,"Yukon, Unorganized, Unorganized",2016A00056001045,Buyer in a group of three or more,55 years old and over,Not first-time home buyer,Admission category not applicable (non-immigrant),Average of price-to-income ratio,Dollars,81,units,0,v1348497720,733.4.4.3.25.8,NaN,..,NaN,NaN,1
17795709,2019,"Yukon, Unorganized, Unorganized",2016A00056001045,Buyer in a group of three or more,55 years old and over,Not first-time home buyer,Admission category not applicable (non-immigrant),Median of the price to income ratio,Dollars,81,units,0,v1348497721,733.4.4.3.25.9,NaN,..,NaN,NaN,1
17795710,2019,"Yukon, Unorganized, Unorganized",2016A00056001045,Buyer in a group of three or more,55 years old and over,Not first-time home buyer,Admission category not applicable (non-immigrant),Average buyer age,Years,308,units,0,v1348497712,733.4.4.3.25.10,NaN,..,NaN,NaN,0
17795711,2019,"Yukon, Unorganized, Unorganized",2016A00056001045,Buyer in a group of three or more,55 years old and over,Not first-time home buyer,Admission category not applicable (non-immigrant),Median buyer age,Years,308,units,0,v1348497713,733.4.4.3.25.11,NaN,..,NaN,NaN,0